version: '3.8'

services:
  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: loggerhead-backend-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      # Add your environment variables here
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env
    volumes:
      # Mount source code for hot reloading
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - loggerhead-dev-network

networks:
  loggerhead-dev-network:
    driver: bridge 